; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	c:\Users\Vadim\documents\visual studio 2010\Projects\Seniv_Lab1\Seniv_Lab1\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

END
